version: '3.8'

services:
  agent-zero-run:
    image: banking
    build: . #this will build from current dir if banking image is not on your system
    ports:
      - "8000:8000"
    env_file:
      - ./.env #env vars if you need them in app container
    volumes:
      - ./:/app    
    restart: "no"
